var getFirstDayOfMonth = function(month, year) {

    if(month == 1){
        return year + '-01-01';
    }
    if(month == 2){
        return year + '-02-01';
    }
    if(month == 3){
        return year + '-03-01';
    }
    if(month == 4){
        return year + '-04-01';
    }
    if(month == 5){
        return year + '-05-01';
    }
    if(month == 6){
        return year + '-06-01';
    }
    if(month == 7){
        return year + '-07-01';
    }
    if(month == 8){
        return year + '-08-01';
    }
    if(month == 9){
        return year + '-09-01';
    }
    if(month == 10){
        return year + '-10-01';
    }
    if(month == 11){
        return year + '-11-01';
    }
    if(month == 12){
        return year + '-12-01';
    }
};

{
    "getFirstDayOfMonth": getFirstDayOfMonth
}
